const products = [
    {
        id: 'twill-shirft-regular-fit',
        name: 'Twill Regular Fit Shirt',
        categoryId: 'upper-body',
        categoryName: 'Upper body',
        price: '19.99',
        image1: '../../clothesphotos/twill-regular-fit-shirt1.jpg',
        image2: '../../clothesphotos/twill-regular-fit-shirt2.jpg'
    },
    {
        id: 'jacquard-knitted-regular-fit-sweater',
        name: 'Jacquard Knitted Regular Fit Sweater',
        categoryId: 'upper-body',
        categoryName: 'Upper body',
        price: '24.99',
        image1: '../../clothesphotos/jacquard-knitted-regular-fit-sweater1.jpg',
        image2: '../../clothesphotos/jacquard-knitted-regular-fit-sweater2.jpg',
    },
    {
        id: 'regular-fit-sweatshirt-with-zipper',
        name: 'Regular Fit Sweatshirt with zipper',
        categoryId: 'upper-body',
        categoryName: 'Upper body',
        price: '17.99',
        image1: '../../clothesphotos/regular-fit-sweatshirt-with-zipper1.jpg',
        image2: '../../clothesphotos/regular-fit-sweatshirt-with-zipper2.jpg',
    },
    {
        id: 'thermally-isolating-in-two-layers-parka',
        name: 'Thermally isolating in two layers Parka',
        categoryId: 'upper-body',
        categoryName: 'Upper body',
        price: '120.00',
        image1: '../../clothesphotos/thermally-isolating-in-two-layers-parka1.jpg',
        image2: '../../clothesphotos/thermally-isolating-in-two-layers-parka2.jpg',
    },
    {
        id: 'oversized-wool-blend-coat',
        name: 'Oversized wool blend Coat',
        categoryId: 'upper-body',
        categoryName: 'Upper body',
        price: '159.99',
        image1: '../../clothesphotos/oversized-wool-blend-coat1.jpg',
        image2: '../../clothesphotos/oversized-wool-blend-coat2.jpg',
    },
    {
        id: 'cotton-twill-shirt',
        name: 'Cotton twill Shirt',
        categoryId: 'upper-body',
        categoryName: 'Upper body',
        price: '19.99',
        image1: '../../clothesphotos/cotton-twill-shirt1.jpg',
        image2: '../../clothesphotos/cotton-twill-shirt2.jpg',   
    },
    {
        id: 'chino-cotton-regular-fit-shorts',
        name: 'Chino cotton Regular Fit shorts',
        categoryId: 'lower-body',
        categoryName: 'Lower body',
        price: '17.99',
        image1: '../../clothesphotos/chino-cotton-regular-fit-short1.jpg',
        image2: '../../clothesphotos/chino-cotton-regular-fit-shorts2.jpg',
    },
    {
        id: 'cotton-fabric-boxers-5-pairs',
        name: 'Cotton fabric boxers, 5 pairs',
        categoryId: 'lower-body',
        categoryName: 'Lower body',
        price: '25.99',
        image1: '../../clothesphotos/cotton-fabric-boxers-5-pairs1.jpg',
        image2: '../../clothesphotos/cotton-fabric-boxers-5-pairs2.jpg',
    },
    {
        id: 'baggy-jeans',
        name: 'Baggy jeans',
        categoryId: 'lower-body',
        categoryName: 'Lower body',
        price: '31.99',
        image1: '../../clothesphotos/baggy-jeans.jpg',
        image2: '../../clothesphotos/baggy-jeans2.jpg',
    },
    {
        id: 'relaxed-fit-cotton-chinos',
        name: 'Relaxed fit cotton chinos',
        categoryId: 'lower-body',
        categoryName: 'Lower body',
        price: '25.99',
        image1: '../../clothesphotos/relaxed-fit-cotton-chinos1.jpg',
        image2: '../../clothesphotos/relaxed-fit-cotton-chinos2.jpg',
    },
    {
        id: 'skinny-fit-cargo-jogging-pants',
        name: 'Skinny fit cargo jogging pants',
        categoryId: 'lower-body',
        categoryName: 'Lower body',
        price: '27.99',
        image1: '../../clothesphotos/skinny-fit-cargo-jogging-pants1.jpg',
        image2: '../../clothesphotos/skinny-fit-cargo-jogging-pants2.jpg',
    },
    {
        id: 'slim-fit-cropped-pants',
        name: 'Slim fit cropped pantss',
        categoryId: 'lower-body',
        categoryName: 'Lower body',
        price: '22.99',
        image1: '../../clothesphotos/slim-fit-cropped-pants1.jpg',
        image2: '../../clothesphotos/slim-fit-cropped-pants2.jpg',
    },
    {
        id: '3-set-rings',
        name: '3 Set Rings',
        categoryId: 'accessories',
        categoryName: 'Accessories',
        price: '5.99',
        image1: '../../clothesphotos/3-set-rings1.jpg',
        image2: '../../clothesphotos/3-set-rings2.jpg',
    },
    {
        id: 'leather-belt',
        name: 'Leather belt',
        categoryId: 'accessories',
        categoryName: 'Accessories',
        price: '15.99',
        image1: '../../clothesphotos/leather-belt1.jpg',
        image2: '../../clothesphotos/leather-belt2.jpg',
    },
    {
        id: 'warm-hat-with-flaps-over-ears',
        name: 'Warm hat with flaps over ears',
        categoryId: 'accessories',
        categoryName: 'Accessories',
        price: '11.99',
        image1: '../../clothesphotos/warm-hat-with-flaps-over-ears1.jpg',
        image2: '../../clothesphotos/warm-hat-with-flaps-over-ears2.jpg',
    },
    {
        id: 'cotton-twill-cap',
        name: 'Cotton twill cap',
        categoryId: 'accessories',
        categoryName: 'Accessories',
        price: '7.99',
        image1: '../../clothesphotos/cotton-twill-cap1.jpg',
        image2: '../../clothesphotos/cotton-twill-cap2.jpg',
    },
    {
        id: 'waist',
        name: 'Waist',
        categoryId: 'accessories',
        categoryName: 'Accessories',
        price: '17.99',
        image1: '../../clothesphotos/waist1.jpg',
        image2: '../../clothesphotos/waist2.jpg',
    },
    {
        id: 'cotton-fisherman-hat',
        name: 'Cotton fisherman hat',
        categoryId: 'accessories',
        categoryName: 'Accessories',
        price: '7.99',
        image1: '../../clothesphotos/cotton-fisherman-hat1.jpg',
        image2: '../../clothesphotos/cotton-fisherman-hat2.jpg',
    },
]

export default products;